// Date: 2013-05-04 20:05:40
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package mods.dnd91.minecraft.hivecraft.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSpawnpool extends ModelBase
{
  //fields
    ModelRenderer bottom;
    ModelRenderer front;
    ModelRenderer back;
    ModelRenderer left;
    ModelRenderer right;
    ModelRenderer liquid;
    ModelRenderer nest;
  
  public ModelSpawnpool()
  {
    textureWidth = 64;
    textureHeight = 128;
    
      bottom = new ModelRenderer(this, 0, 64);
      bottom.addBox(-8F, 0F, -8F, 16, 1, 16);
      bottom.setRotationPoint(0F, 23F, 0F);
      bottom.setTextureSize(64, 128);
      bottom.mirror = true;
      setRotation(bottom, 0F, 0F, 0F);
      front = new ModelRenderer(this, 0, 0);
      front.addBox(-8F, -8F, -1F, 16, 15, 1);
      front.setRotationPoint(0F, 16F, -7F);
      front.setTextureSize(64, 128);
      front.mirror = true;
      setRotation(front, 0F, 0F, 0F);
      back = new ModelRenderer(this, 0, 17);
      back.addBox(-8F, -8F, 0F, 16, 15, 1);
      back.setRotationPoint(0F, 16F, 7F);
      back.setTextureSize(64, 128);
      back.mirror = true;
      setRotation(back, 0F, 0F, 0F);
      left = new ModelRenderer(this, 0, 33);
      left.addBox(0F, -8F, -7F, 1, 15, 14);
      left.setRotationPoint(7F, 16F, 0F);
      left.setTextureSize(64, 128);
      left.mirror = true;
      setRotation(left, 0F, 0F, 0F);
      right = new ModelRenderer(this, 30, 33);
      right.addBox(-1F, -8F, -7F, 1, 15, 14);
      right.setRotationPoint(-7F, 16F, 0F);
      right.setTextureSize(64, 128);
      right.mirror = true;
      setRotation(right, 0F, 0F, 0F);
      liquid = new ModelRenderer(this, 0, 101);
      liquid.addBox(-7F, 0F, -7F, 14, 13, 14);
      liquid.setRotationPoint(0F, 10F, 0F);
      liquid.setTextureSize(64, 128);
      liquid.mirror = true;
      setRotation(liquid, 0F, 0F, 0F);
      nest = new ModelRenderer(this, 40, 0);
      nest.addBox(-3F, 0F, -3F, 5, 9, 5);
      nest.setRotationPoint(0F, 9F, 0F);
      nest.setTextureSize(64, 128);
      nest.mirror = true;
      setRotation(nest, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    bottom.render(f5);
    front.render(f5);
    back.render(f5);
    left.render(f5);
    right.render(f5);
    liquid.render(f5);
    nest.render(f5);
  }
  
  public void renderModel(float f5){
	  bottom.render(f5);
	    front.render(f5);
	    back.render(f5);
	    left.render(f5);
	    right.render(f5);
	    nest.render(f5);
	    liquid.render(f5);
	    
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
   // super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
