// Date: 2013-05-21 16:25:27
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package mods.dnd91.minecraft.hivecraft.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBuilderMagic extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer firstsegment;
    ModelRenderer secondsegment;
    ModelRenderer thirdsegment;
    ModelRenderer forthsegment;
    ModelRenderer fithsegment;
  
  public ModelBuilderMagic()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-3F, -3F, -6F, 6, 6, 6);
      head.setRotationPoint(0F, 21F, -2F);
      head.setTextureSize(128, 128);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      firstsegment = new ModelRenderer(this, 0, 13);
      firstsegment.addBox(-8F, -13F, 0F, 16, 16, 4);
      firstsegment.setRotationPoint(0F, 21F, -2F);
      firstsegment.setTextureSize(128, 128);
      firstsegment.mirror = true;
      setRotation(firstsegment, 0F, 0F, 0F);
      secondsegment = new ModelRenderer(this, 0, 34);
      secondsegment.addBox(-10F, -17F, 0F, 20, 20, 14);
      secondsegment.setRotationPoint(0F, 21F, 2F);
      secondsegment.setTextureSize(128, 128);
      secondsegment.mirror = true;
      setRotation(secondsegment, 0F, 0F, 0F);
      thirdsegment = new ModelRenderer(this, 0, 69);
      thirdsegment.addBox(-7F, -11F, 0F, 14, 14, 4);
      thirdsegment.setRotationPoint(0F, 21F, 16F);
      thirdsegment.setTextureSize(128, 128);
      thirdsegment.mirror = true;
      setRotation(thirdsegment, 0F, 0F, 0F);
      forthsegment = new ModelRenderer(this, 0, 88);
      forthsegment.addBox(-6F, -9F, 0F, 12, 12, 5);
      forthsegment.setRotationPoint(0F, 21F, 20F);
      forthsegment.setTextureSize(128, 128);
      forthsegment.mirror = true;
      setRotation(forthsegment, 0F, 0F, 0F);
      fithsegment = new ModelRenderer(this, 0, 106);
      fithsegment.addBox(-4F, -5F, 0F, 8, 8, 4);
      fithsegment.setRotationPoint(0F, 21F, 25F);
      fithsegment.setTextureSize(128, 128);
      fithsegment.mirror = true;
      setRotation(fithsegment, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(entity, f, f1, f2, f3, f4, f5);
    head.render(f5);
    firstsegment.render(f5);
    secondsegment.render(f5);
    thirdsegment.render(f5);
    forthsegment.render(f5);
    fithsegment.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
